config/routes.rb
Rails.application.routes.draw do
  root 'authors#index'
  resources :authors do
    resources :posts, shallow:true 
  end

end

app/models/author.rb
class Author < ActiveRecord::Base
  validates :first_name, :last_name, presence: true, length: {in: 4...20}
  validates :age, numericality: true 
  has_many :posts, dependent: :destroy
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :body, :category, presence:true 
  validates :title, length: {minimum:3}
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def edit
    @author = Author.find(params[:id])
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new author_params
    if @author.save
      redirect_to authors_path
    else
      render :new
    end
  end

  def update
    @author = Author.find(params[:id])
    @author.update_attributes author_params
    if @author.save
      redirect_to author_path(@author)
    else 
      render :edit
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    redirect_to authors_path
  end

  private
  def author_params
    params.require(:author).permit(:first_name, :last_name, :age)
  end  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @author = Author.find(params[:author_id]) 
    @posts = @author.posts
  end

  def edit
    @post = Post.find(params[:id])
    @author = @post.author
  end

  def show
    @post = Post.find(params[:id])
    @author = @post.author
  end

  def new
    @author = Author.find(params[:author_id])
    @post = Post.new 
  end

  def create
    @author = Author.find(params[:author_id])
    @post = Post.new post_params
    @post.author = @author 
    @author.posts << @post 
    if @post.save
      redirect_to author_posts_path(@author)
    else
      render :new 
    end
  end

  def update
    @post = Post.find(params[:id])
    @post.update_attributes post_params
    @author = @post.author
      if @post.save 
        redirect_to post_path(@post)
      else
      render :edit 
      end 
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to author_posts_path(post.author)
  end

  private 
  def post_params
    params.require(:post).permit(:title, :body, :category, :author_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/edit.html.erb
<%= render "shared/navbar" %>
<div class="container-fluid">

  <% if @author.errors.any?%>
  <% @author.errors.full_messages.each do |error|%>
  <p class = "text-danger">
    <%= error %>
  </p>
  <% end %>
  <% end %>

  <h2 class="text-center">Add Author Here:</h2>
 <%= simple_form_for(@author, :html => { :class => "form-inline" }) do |f|%>
<div class = row>
<div class="col-md-2 col-md-offset-2">
  <%= f.input :first_name, error_html: { id: 'error'} %>
  </div>
  <div class = "col-md-1"></div>
    <div class="col-md-2">
  <%= f.input :last_name, error_html: { id: 'error'} %>
  </div>
  <div class = "col-md-1"></div>
    <div class="col-md-2">
  <%= f.input :age, error_html: { id: 'error'} %>
  </div>
  </div>

  <br>
  <div class ="row">
  <div class = "col-md-3 col-md-offset-5">
  <%= f.submit "Edit Author", class: 'btn btn-primary' %>
  <% end %>
  </div>
  </div>
</div>

app/views/authors/index.html.erb
<%= render "shared/navbar" %>

<div class="container-fluid">

<h2 class = "text-center">Authors:</h2>
<br>

<!-- <table style = "border: 1px solid black; border-collapse: collapse"> -->
<div class="row">
<div class ="col-md-10 col-md-offset-1">
<table class ="table table-striped">
<tr>
<th>First Name</th>
<th>Last Name</th>
<th>Age</th>
<th>Info</th>
<th>Edit</th>
<th>Delete</th>
</tr>
<% @authors.each do |author| %>
  <tr >
    <td ><%=author.first_name  %></td>
    <td ><%= author.last_name %></td>
    <td><%= author.age %></td>
    <td><%= link_to('Info', author_path(author), {class: "btn-xs btn-info"})%></td>
    <td><%= link_to('Edit', edit_author_path(author), {class: "btn-xs btn-info"})%></td>
    <td><%= link_to('Delete',author_path(author), method: :delete, data: { confirm: "Are you sure?" }, class: "btn-xs btn-danger")%></td>
  </tr>
  <%end %>
</table>
</div>
</div>

<div class="row">
<div class ="col-md-2 col-md-offset-1">
<%=  link_to('Add new author', new_author_path, {class: "btn btn-primary"}) %>
</div>
</div>
</div>

app/views/authors/new.html.erb
<%= render "shared/navbar" %>
<div class="container-fluid">

<h2 class ="text-center">Add Author Here:</h2>

<%= simple_form_for(@author, :html => { :class => "form-inline autofocus"}) do |f|%>
<div class = row>
<div class="col-md-2 col-md-offset-2">
  <%= f.input :first_name, error_html: { id: 'error'}%>
</div>
<div class = "col-md-1"></div>
  <div class="col-md-2">
  <%= f.input :last_name, error_html: { id: 'error'} %>
  </div>
  <div class = "col-md-1"></div>
 <div class="col-md-2">
  <%= f.input :age, error_html: { id: 'error'} %>
  </div>
  </div>
  <br>
  <div class ="row">
  <div class ="col-md-3 col-md-offset-5">
  <%= f.submit "Add Author", class: 'btn btn-primary' %>
  </div>
  </div>
  <% end %>
</div>

app/views/authors/show.html.erb
<%= render "shared/navbar" %>
<div class="container-fluid">

<h2 class = "text-center">Author:</h2>

<!-- <table style = "border: 1px solid black; border-collapse: collapse"> -->
<div class="row">
<div class ="col-md-10 col-md-offset-1">
<table class ="table table-striped">
<tr>
<th>First Name</th>
<th>Last Name</th>
<th>Age</th>
</tr>
  <tr >
    <td ><%=@author.first_name  %></td>
    <td ><%= @author.last_name %></td>
    <td><%= @author.age %></td>
  </tr>
</table>
</div>
</div>
<div class="row">
<div class ="col-md-2 col-md-offset-1">
<%=  link_to('See Blog Posts', author_posts_path(@author), {class: "btn btn-primary"}) %>
<br><br>
<%=  link_to('Back to Authors', root_path, {class: "btn btn-primary"}) %>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogLab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<%= render "shared/navbar" %>
<div class="container-fluid">


  <h2 class="text-center">Edit Post Here:</h2>
 <%= simple_form_for(@post, :html => { :class => "form-inine" }) do |f|%>
<div class="row">
<div class = "col-md-2 col-md-offset-2">
  <%= f.input :title, error_html: { id: 'error'} %>
 </div>
 <div class ="col-md-1"> </div>
 <div class = "col-md-2 ">
 <%= f.input :category, error_html: { id: 'error'}%>
 </div>
 <div class ="col-md-1"> </div>
 <div class = "col-md-2 ">
  <%= f.input :body, error_html: { id: 'error'} %>
  </div>
  </div>

  <br>
    <div class ="row">
  <div class = "col-md-2 col-md-offset-2">
  <%=  link_to('Back to Posts',author_posts_path(@author) , {class: "btn btn-primary"}) %>
  <br><br>
    </div>
  <div class ="col-md-3 col-md-offset-1">
  <%= f.submit "Edit Post", class: 'btn btn-primary' %>
  <% end %>
  </div>
  </div>
</div>

app/views/posts/index.html.erb
<%= render "shared/navbar" %>
<div class="container-fluid">

<h2 class = "text-center"><%= @author.first_name%> <%= @author.last_name %> Posts</h2>

<!-- <table style = "border: 1px solid black; border-collapse: collapse"> -->

<div class="row">
<div class ="col-md-10 col-md-offset-1">
<table class ="table table-striped">
<tr>
<th>Title</th>
<th>Category</th>
<th>Info</th>
<th>Edit</th>
<th>Delete</th>
</tr>
<% @posts.each do |post| %>
  <tr >
    <td ><%=post.title  %></td>
    <td><%= post.category %></td>
    <td><%= link_to('Info', post_path(post), {class: "btn-xs btn-info"})%></td>
    <td><%= link_to('Edit', edit_post_path(post), {class: "btn-xs btn-info"})%></td>
    <td><%= link_to('Delete',post_path(post), method: :delete, data: { confirm: "Are you sure?" },class: "btn-xs btn-danger")%></td>
  </tr>
  <%end %>
</table>
</div>
</div>
<div class="row">
<div class ="col-md-2 col-md-offset-1">
<%=  link_to('Add new Post', new_author_post_path, {class: "btn btn-primary"}) %>

</div>
</div>

app/views/posts/new.html.erb
<%= render "shared/navbar" %>
<div class="container-fluid">

  <h2 class ="text-center">Add Blog Post Here:</h2>
  <br>

<%= simple_form_for([@author,@post], :html => { :class => "form-inline"}) do |f|%>
<div class = row>
<div class="col-md-2 col-md-offset-2">
  <%= f.input :title, error_html: { id: 'error'}%>
<br>
</div>
<div class = "col-md-1"></div>
  <div class="col-md-2">
  <%= f.input :category, error_html: { id: 'error'} %>
<br>
  </div>
  <div class = "col-md-1"></div>
 <div class=" col-md-2">
  <%= f.input :body, error_html: { id: 'error'} %>
<br>
  </div>
  </div>
  <br>
  <div class ="row">
  <div class = "col-md-2 col-md-offset-2">
  <%=  link_to('Back to Author', author_posts_path(@author), {class: "btn btn-primary"}) %>
  </div>
  <div class ="col-md-3 col-md-offset-1">
  <%= f.submit "Add Post", class: 'btn btn-primary' %>
  </div>
  </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<%= render "shared/navbar" %>
<div class="container-fluid">

<h2 class = "text-center"><%= @post.title%></h2>

<!-- <table style = "border: 1px solid black; border-collapse: collapse"> -->
<div class="row">
<div class ="col-md-10 col-md-offset-1">
<table class ="table table-striped">
<tr>
<th>Title</th>
<th>Category</th>
<th>Edit</th>
<th>Delete</th>
</tr>
  <tr >
    <td ><%=@post.title %></td>
    <td><%= @post.category %></td>
    <td><%= link_to('Edit', edit_post_path(@post), {class: "btn-xs btn-info"})%></td>
    <td><%= link_to('Delete',post_path(@post), method: :delete, data: { confirm: "Are you sure?" },class: "btn-xs btn-danger")%></td>
  </tr>
</table>
</div>
</div>
<div class="row">
<div class ="col-md-10 col-md-offset-1">
<p class = "text-center"><%=@post.body%></p>
<br>
<%=  link_to('Back to Author', author_posts_path(@author), {class: "btn btn-primary"}) %>
</div>
</div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/authors">Home</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>